import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { IoIosCall } from "react-icons/io";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <div className="fixed bottom-10 right-10 z-10 bg-white rounded-full p-1 animate-bounce h-10 w-10">
        <IoIosCall className="h-full w-full" />
      </div>
      <body className={`${inter.className} app-scrollbar`}>{children}</body>
    </html>
  );
}
